### ISSUE TITLE
Build instructions

### ISSUE THREAD

**Issue by pathawks** [Kreeblah/NES20Tool#3]
Please provide build instructions. I tried running `go build` to no avail:

```text
$ go build
NES20Tool.go:23:2: cannot find package "NES20Tool/FDSTool" in any of:
	/usr/local/Cellar/go/1.15.8/libexec/src/NES20Tool/FDSTool (from $GOROOT)
	~/go/src/NES20Tool/FDSTool (from $GOPATH)
NES20Tool.go:24:2: cannot find package "NES20Tool/FileTools" in any of:
	/usr/local/Cellar/go/1.15.8/libexec/src/NES20Tool/FileTools (from $GOROOT)
	~/go/src/NES20Tool/FileTools (from $GOPATH)
NES20Tool.go:25:2: cannot find package "NES20Tool/NESTool" in any of:
	/usr/local/Cellar/go/1.15.8/libexec/src/NES20Tool/NESTool (from $GOROOT)
	~/go/src/NES20Tool/NESTool (from $GOPATH)
NES20Tool.go:26:2: cannot find package "NES20Tool/ProcessingTools" in any of:
	/usr/local/Cellar/go/1.15.8/libexec/src/NES20Tool/ProcessingTools (from $GOROOT)
	~/go/src/NES20Tool/ProcessingTools (from $GOPATH)
```

**Comment by Kreeblah** [comment]
I'd been building out of ~/go/src/NES20Tool, rather than ~/go/src/github.com/Kreeblah/NES20Tool, which is where `go get` puts things.  But, it probably makes more sense to use the latter path since it makes things easier for the Go tooling.

So, I just updated the import statements since that will make things easier for folks.  I just tested in a fresh VM, and the following works now:

    $ go get github.com/Kreeblah/NES20Tool
    $ go build github.com/Kreeblah/NES20Tool

I also added build instructions to the readme, since that's never a bad thing to have.
